### ISSUE TITLE
odoo12下出现异常

### ISSUE THREAD

**Issue by kakaok** [ScottAI/Odoo-Python-ERP-#1]
按照教程一步步来操作，发现有个bug
![image](https://user-images.githubusercontent.com/10599857/58399642-68e29500-808b-11e9-86ff-ae45082f65bd.png)

**Comment by kakaok** [comment]
bug-manager 这个模块安装完后没有发现顶级菜单显示出来，后台也没有对应的顶级菜单
![image](https://user-images.githubusercontent.com/10599857/58400484-be1fa600-808d-11e9-95fb-193f10d4605d.png)

**Comment by kakaok** [comment]
odoo12下需要将 __manifest__ 中的设置修改下才会显示
    'application': True,
    'installable': True,

**Comment by ScottAI** [comment]
> 按照教程一步步来操作，发现有个bug
> ![image](https://user-images.githubusercontent.com/10599857/58399642-68e29500-808b-11e9-86ff-ae45082f65bd.png)

这个问题解决了吗，是因为id里面使用了 . 造成的吗，不过我这边试了下，在odoo12的环境下是可以的

**Comment by ScottAI** [comment]
> odoo12下需要将 **manifest** 中的设置修改下才会显示
> 'application': True,
> 'installable': True,

我重新测试了下，我们没有设置这两项，在我的odoo12环境是可以安装的：
# -*- coding: utf-8 -*-
{
    'name': "myTest",

    'summary': """
        Short (1 phrase/line) summary of the module's purpose, used as
        subtitle on modules listing or apps.openerp.com""",

    'description': """
        Long description of module's purpose
    """,

    'author': "My Company",
    'website': "http://www.yourcompany.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['base'],

    # always loaded
    'data': [
        # 'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
}

安装后效果：
![Uploading image.png…]()

application不为True在搜索的时候可能看不到，因为默认是限制为  Apps 的，如果去掉这个限制就可以搜到 add on了。一般纯技术性的add on不需要设置，单独的系统设置上比较好，因为确实是Application。

感谢您的问题，可以让更多的人看到。

按照官方文档说明，application 和 installable默认都是false的。不过我也确实都没有设置，也是可以安装的，我觉得application主要是在apps里面搜索的方便，与是否显示顶级菜单没有关系。

我的环境：
wind 10
pg9.5
python3.5
odoo  12.0
